### ISSUE TITLE
Prepend text "GrPPI:" to all messages

### ISSUE THREAD

**Issue by jdgarciauc3m** [danielmartinezdavies/llvm-project-clang-tidy-check#1]
It is difficult to know which check is generating a message.

I suggest to prepend all messages wigth "GrPPI: " to identify the source.

Example: 

Instead of:

`Clang-Tidy: Map pattern detected. Loop can be parallelized.` 

It would be nice to have:

`Clang-Tidy: GrPPI: Map pattern detected. Loop can be parallelized.`

**Comment by dmardavies** [comment]
Sounds like a good suggestion. As I have added it I will close this issue.
