### ISSUE TITLE
Loop non-const max iterations is not accepted in parallel loop

### ISSUE THREAD

**Issue by jdgarciauc3m** [danielmartinezdavies/llvm-project-clang-tidy-check#2]
When analyzing the following function:
```c++
auto add(const std::vector<double> & v, const std::vector<double> & w) {
  std::vector<double> r(v.size());
  for (std::size_t i=0; i<v.size(); ++i) {
    r[i] = v[i] + w[i];
  }
  return r;
}
```
The checker says "No parallelization possible" without telling why.

On one hand, in general, messages should be more self-explanatory or provide a link to documentation.

On the other hand, it seems that the issue here is that variable i is compared to the expression v.size(). This should be considered valid.

**Comment by dmardavies** [comment]
The use case has been resolved. Messages have been modified to be as minimal as possible by default but have an option to make them more verbose and explanatory. Therefore I'm closing this issue.
